# TCL File Generated by Component Editor 8.1
# Mon Jun 22 12:24:35 JST 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | can_top "can_top" v2.5
# | null 2009.06.22.12:24:35
# | 
# | 
# | C:/altera/UserDesign/2s180_single_ice+CANC_New/canc/hdl/can_top.v
# | 
# |    ./can_top.v syn, sim
# |    ./can_acf.v syn, sim
# |    ./can_bsp.v syn, sim
# |    ./can_btl.v syn, sim
# |    ./can_crc.v syn, sim
# |    ./can_defines.v syn, sim
# |    ./can_fifo.v syn, sim
# |    ./can_ibo.v syn, sim
# |    ./can_register.v syn, sim
# |    ./can_register_asyn.v syn, sim
# |    ./can_register_asyn_syn.v syn, sim
# |    ./can_register_syn.v syn, sim
# |    ./can_registers.v syn, sim
# |    ./can_rxmboxacf.v syn, sim
# |    ./C:/altera/UserDesign/2s180_single_ice+CANC_New/canc/can_top.v syn
# | 
# +-----------------------------------


# +-----------------------------------
# | module can_top
# | 
set_module_property NAME can_top
set_module_property VERSION 2.5
set_module_property GROUP ""
set_module_property DISPLAY_NAME can_top
set_module_property TOP_LEVEL_HDL_FILE can_top.v
set_module_property TOP_LEVEL_HDL_MODULE can_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file can_top.v {SYNTHESIS SIMULATION}
add_file can_acf.v {SYNTHESIS SIMULATION}
add_file can_bsp.v {SYNTHESIS SIMULATION}
add_file can_btl.v {SYNTHESIS SIMULATION}
add_file can_crc.v {SYNTHESIS SIMULATION}
add_file can_defines.v {SYNTHESIS SIMULATION}
add_file can_fifo.v {SYNTHESIS SIMULATION}
add_file can_ibo.v {SYNTHESIS SIMULATION}
add_file can_register.v {SYNTHESIS SIMULATION}
add_file can_register_asyn.v {SYNTHESIS SIMULATION}
add_file can_register_asyn_syn.v {SYNTHESIS SIMULATION}
add_file can_register_syn.v {SYNTHESIS SIMULATION}
add_file can_registers.v {SYNTHESIS SIMULATION}
add_file can_rxmboxacf.v {SYNTHESIS SIMULATION}
add_file C:/altera/UserDesign/2s180_single_ice+CANC_New/canc/can_top.v SYNTHESIS
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter Tp INTEGER 1
set_parameter_property Tp DISPLAY_NAME Tp
set_parameter_property Tp UNITS None
set_parameter_property Tp AFFECTS_PORT_WIDTHS true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 addressSpan 1024
set_interface_property avalon_slave_0 bridgesToMaster ""
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 minimumUninterruptedRunLength 1
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ASSOCIATED_CLOCK clock_sink

add_interface_port avalon_slave_0 av_cs_i chipselect Input 1
add_interface_port avalon_slave_0 av_wr_i write Input 1
add_interface_port avalon_slave_0 av_adr_i address Input 8
add_interface_port avalon_slave_0 av_dat_i writedata Input 32
add_interface_port avalon_slave_0 av_dat_o readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

add_interface_port conduit_end tx_o export Output 1
add_interface_port conduit_end rx_i export Input 1
add_interface_port conduit_end clkout_o export Output 1
add_interface_port conduit_end bus_off_on export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink ptfSchematicName ""

add_interface_port clock_sink clk_i clk Input 1
add_interface_port clock_sink av_rst_i reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt_sender
# | 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave_0

set_interface_property interrupt_sender ASSOCIATED_CLOCK clock_sink

add_interface_port interrupt_sender irq_on irq_n Output 1
# | 
# +-----------------------------------
